'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AUCTION.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _039a6215_1_6_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("039a6215_1_6_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0f02c219dc3645ad9f6622fa535fb049__low_cost_tech_news() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("0f02c219dc3645ad9f6622fa535fb049--low-cost-tech-news", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0f6e7dd6ae0c86f51c26868a85238648__meiji_vase() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("0f6e7dd6ae0c86f51c26868a85238648--meiji-vase", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _12e8d1ddf5724ed8b5910734f1dfed67_RF14_35mm_f4L_IS_USM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("12e8d1ddf5724ed8b5910734f1dfed67_RF14-35mm+f4L+IS+USM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1636094253_2135() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1636094253-2135", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _17_avatar_man_nodding_lineal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("17-avatar-man-nodding-lineal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _17_avatar_man_nodding_lineal1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("17-avatar-man-nodding-lineal1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _193113951908_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("193113951908-1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2016_1st_place_crystal_classic_sandsculpting_competition_siesta_key() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2016-1st-place-crystal-classic-sandsculpting-competition-siesta-key", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _21_avatar_lineal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("21-avatar-lineal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _21_avatar_lineal1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("21-avatar-lineal1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _21_avatar_lineal2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("21-avatar-lineal2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _300x300() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("300x300", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _34_code_outline() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("34-code-outline", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _41xiaUAU9NL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("41xiaUAU9NL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _51BEnCiD_VL__SY355_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("51BEnCiD+VL._SY355_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _54ad748de4b058ea7711d504() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("54ad748de4b058ea7711d504", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _55440() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("55440", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _61C_IWVh2pL__UY500_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("61C-IWVh2pL._UY500_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _61HkxdsBSXL__UY625_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("61HkxdsBSXL._UY625_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _61HkxdsBSXL1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("61HkxdsBSXL1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _71mdoicpqWL__AC_SL1500_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("71mdoicpqWL._AC_SL1500_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _71R6LTyMphL__SY355_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("71R6LTyMphL._SY355_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _71x3_vIYw2L__AC_UL320_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("71x3-vIYw2L._AC_UL320_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _758841c0acc611d8430cf9d4a4fa94693bf70392() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("758841c0acc611d8430cf9d4a4fa94693bf70392", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _77636F_pds0011() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("77636F_pds0011", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _81dBU_dhARL__AC_SL1500_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("81dBU+dhARL._AC_SL1500_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _8d0db401031e4decbdf0d82dce54c796_G7_X_mkIII_BK_Front() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("8d0db401031e4decbdf0d82dce54c796_G7+X+mkIII+BK+Front", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property a_mdi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("a_mdi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property a_mdi1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("a_mdi1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property a708f74b737c592d8691bf5b28fa2652__yi_sun_sin_south_korea() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("a708f74b737c592d8691bf5b28fa2652--yi-sun-sin-south-korea", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property access_page_pic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("access_page_pic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property access_page_pic1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("access_page_pic1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property afd86f95484148860e221aee8b016737() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("afd86f95484148860e221aee8b016737", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property airMail_stamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("airMail_stamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property appl_loptop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("appl loptop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property appl_loptop3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("appl loptop3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property appl_loptop4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("appl loptop4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property appl_loptop5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("appl loptop5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property apple_iphone_14_pro_max_256_gb_deep_purple_6_gb_ram_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("apple-iphone-14-pro-max-256-gb-deep-purple-6-gb-ram-", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arts_poductinfo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arts_poductinfo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arts_poductinfo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arts_poductinfo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arts1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arts1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property asus_laptops_v9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("asus-laptops-v9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property auc_img() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("auc_img", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property auc_img1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("auc_img1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property aucMDI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aucMDI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property auction() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("auction", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ba3f5338693ea00fb8e613a22f7e196e() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ba3f5338693ea00fb8e613a22f7e196e", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ba3f5338693ea00fb8e613a22f7e196e1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ba3f5338693ea00fb8e613a22f7e196e1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property baby_girls_boy_newborn_kids_clothes_clothing_long_sleeve_dresses_winter_sky_b_lue_3t_kids_233_1445x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("baby-girls-boy-newborn-kids-clothes-clothing-long-sleeve-dresses-winter-sky-b-lue"& _ 
                        "-3t-kids-233_1445x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property background1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property background11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property background110() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background110", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property background12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property background13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property background14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property background15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property background16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property background17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property background18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property background19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bg_auction() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_auction", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BG1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property buddha() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buddha", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property camera() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("camera", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property camera1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("camera1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property camera11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("camera11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Canon_EF_S_18_55mm_f4_5_6_IS_STM_Lens_Online_Buy_Mumbai_India_2_500x500() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Canon-EF-S-18-55mm-f4-5.6-IS-STM-Lens-Online-Buy-Mumbai-India-2-500x500", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ceramic_pottery_500x500() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ceramic-pottery-500x500", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property chinse_fig() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chinse_fig", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Clars() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Clars", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property coding_gif() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("coding_gif", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property d9h2dp2euvmucluf5djz4q384zc7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("d9h2dp2euvmucluf5djz4q384zc7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dell_laptops_v9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dell-laptops-v9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property download() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Drone_1__3__min_1000x1000() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Drone 1 (3)-min-1000x1000", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property e024923fbeb237384d84bf90f49c1351() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("e024923fbeb237384d84bf90f49c1351", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property electronics1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("electronics1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property emblom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("emblom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property emblom1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("emblom1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fashion1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fashion1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gpay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gpay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property greek() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("greek", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property holkar_state_stamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("holkar_state_stamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property How_much_Johannes_Reekers_painting_worth() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("How-much-Johannes-Reekers-painting-worth", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hp_laptops_v9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hp-laptops-v9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_asset() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image-asset", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ind_stamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ind_stamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ipad_10th_gen_finish_select_202212_pink_wifi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ipad-10th-gen-finish-select-202212-pink-wifi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property istockphoto_185295219_612x612() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("istockphoto-185295219-612x612", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kamakura() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kamakura", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kids() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kids", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kids_shoes_1563014292_4996704() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kids-shoes-1563014292-4996704", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kidsfashion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kidsfashion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kikumon_stamp_of_japan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kikumon-stamp-of-japan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lady() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lady", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property laptop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("laptop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lenovo_thinkpad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lenovo_thinkpad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mac() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mac", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property main_image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main-image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property manstyle1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manstyle1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property manstyle11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manstyle11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MDI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MDI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mdi_auc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mdi_auc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mdi1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mdi1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mdi3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mdi3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mdi31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mdi31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mdi32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mdi32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Media_product_info() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Media_product_info", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mens_Fashion_Accessories_800x534() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mens-Fashion-Accessories-800x534", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MKU93() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MKU93", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MKU93_VW_34FR_watch_40_alum_starlight_cell_se_VW_34FR_WF_CO_GEO_IN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MKU93_VW_34FR+watch-40-alum-starlight-cell-se_VW_34FR_WF_CO_GEO_IN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MKU93_VW_PF_watch_40_alum_starlight_cell_se_VW_PF_WF_CO_GEO_IN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MKU93_VW_PF+watch-40-alum-starlight-cell-se_VW_PF_WF_CO_GEO_IN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property motorola_edge_20_fusion_128_gb_electric_graphite_6_gb_ram___4_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("motorola-edge-20-fusion-128-gb-electric-graphite-6-gb-ram- (4)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MP000000013748431_437Wx649H_202207101148401() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MP000000013748431_437Wx649H_202207101148401", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nataraja() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nataraja", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ninja3_black_01_400x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ninja3_black_01_400x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property occasion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("occasion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property p01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("p01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property p1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("p1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property p11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("p11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property password_forgot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("password-forgot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property payapl_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("payapl_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property paytm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paytm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property phonepay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("phonepay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pro_info() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pro_info", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property product_info_gif() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("product_info_gif", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pTron_FORCE_X10_Smart_Watch_493627249_i_1_1200Wx1200H() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pTron-FORCE-X10-Smart-Watch-493627249-i-1-1200Wx1200H", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Quadcopter_hd_camera_drone_SDL835268691_1_eee9e() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Quadcopter-hd-camera-drone-SDL835268691-1-eee9e", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property republic_of_korea_flag_on_postage_stamp_2A7TFA8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("republic-of-korea-flag-on-postage-stamp-2A7TFA8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RHINO_COMMEMORATIVE_STAMP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RHINO-COMMEMORATIVE-STAMP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sarangi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sarangi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SBC_baby_boy_06__SY530_QL85_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SBC-baby-boy_06._SY530_QL85_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SBC_baby_boy_061() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SBC-baby-boy_061", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screenshot_2023_02_02_145323() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screenshot 2023-02-02 145323", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shoes_on_amazon_amazon_running_shoes_91781166() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shoes-on-amazon-amazon-running-shoes-91781166", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property smartph() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smartph", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property stamps1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stamps1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Style_Accessories_for_Men() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Style-Accessories-for-Men", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property taj_stamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("taj_stamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property THAI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("THAI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property train_stamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("train_stamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property train2_stamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("train2_stamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tumblr_ociwti5VGH1uceufyo1_1280() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tumblr_ociwti5VGH1uceufyo1_1280", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property vivo_v25_pro_256_gb_sailing_blue_12_gb_ram___2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vivo-v25-pro-256-gb-sailing-blue-12-gb-ram- (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Webp_net_resizeimage_4_1200x900() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Webp.net-resizeimage-4-1200x900", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property why_you_should_own_koban_stamps_of_japan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("why-you-should-own-koban-stamps-of-japan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WILD_LIFE_SERIES_INDIAN_LION_COMMEMORATIVE_STAMP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WILD-LIFE-SERIES-INDIAN-LION-COMMEMORATIVE-STAMP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WILD_LIFE_SERIES_INDIAN_LION_COMMEMORATIVE_STAMP1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WILD-LIFE-SERIES-INDIAN-LION-COMMEMORATIVE-STAMP1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property womanshoes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("womanshoes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property womanshoes1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("womanshoes1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property womanstyle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("womanstyle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property women_shoes_mobile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("women-shoes-mobile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property womens_accessories_1621425704_5828046() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("womens-accessories-1621425704-5828046", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
